# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db550b09a80506294afa1e25fab5e7d9f415ca101a8e3f06304d9f55162b893e5f0809767482ef4dfc133a294de44bfb58ca4b94f5a46c75a424ab9a1cc330ac

test:
  secret_key_base: 36d3e4b4636d2a91c3f902fe0ffb87bb2d3b3a22b057d9de880476fccb9affb1afb6f96e469fc7c65a1d9df8b349f5c18d451cccdeca8975d0c3a171c1a70a9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
